# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 08:46
from __future__ import unicode_literals

import account.models
import account.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170821_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANTLRScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_score', models.IntegerField()),
                ('parallelism_score', models.IntegerField()),
                ('synchronization_score', models.IntegerField()),
                ('flow_control_score', models.IntegerField()),
                ('user_interactivity_score', models.IntegerField()),
                ('logical_thinking_score', models.IntegerField()),
                ('data_representation_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-username',),
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u4f5c\u54c1\u540d\u79f0')),
                ('file', models.FileField(storage=account.storage.OverwriteStorage(), upload_to=account.models.get_upload_path, verbose_name='\u4e0b\u8f7d\u5730\u5740')),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('image', models.ImageField(null=True, storage=account.storage.OverwriteStorage(), upload_to=account.models.get_image_path)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.User', verbose_name='\u4f5c\u8005')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.CharField(max_length=100)),
                ('production_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Production')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comment', models.TextField(max_length=2000, null=True)),
                ('production_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Production')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.BaseUser')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField(null=True)),
                ('grade', models.CharField(max_length=30, null=True)),
                ('student_id', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_school', to='account.School')),
                ('school_second', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_school_2', to='account.School')),
            ],
            options={
                'ordering': ('-username',),
            },
            bases=('account.baseuser',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.BaseUser')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'ordering': ('-username',),
            },
            bases=('account.baseuser',),
        ),
        migrations.AddField(
            model_name='class',
            name='school_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.School'),
        ),
        migrations.AddField(
            model_name='antlrscore',
            name='production_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Production'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_class', to='account.Class'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class_second',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_class_2', to='account.Class'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='account.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set([('school_name', 'class_name')]),
        ),
    ]
