# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170821_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antlrscore',
            name='production_id',
        ),
        migrations.RemoveField(
            model_name='production',
            name='author',
        ),
        migrations.RemoveField(
            model_name='productionhint',
            name='production_id',
        ),
        migrations.RemoveField(
            model_name='teacherscore',
            name='production_id',
        ),
        migrations.DeleteModel(
            name='ANTLRScore',
        ),
        migrations.DeleteModel(
            name='Production',
        ),
        migrations.DeleteModel(
            name='ProductionHint',
        ),
        migrations.DeleteModel(
            name='TeacherScore',
        ),
    ]
